In [9]:
import numpy as np
np.int = np.int32
np.float = np.float64
np.bool = np.bool_
import tensorflow as tf
'''
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0],True)
'''


In [18]:
# operations
X = tf.random.normal((1,3),mean=0,stddev=1)
Y= tf.random.uniform((1,3),minval=0,maxval=1)
Z=tf.multiply(X,Y)
Z

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.32687557,  0.05809901, -0.8827186 ]], dtype=float32)>

In [19]:
X1=tf.constant([1,2,3])
Y1=tf.constant([4,5,6])
Z1=tf.tensordot(X1,Y1,axes=1)
Z1

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [24]:
# indexing 

X1[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [30]:
X2 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
X2[0:2,:]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [34]:
# reshaping 
X3 = tf.range(9)

X3 = tf.reshape(X3,(3,3))

X3 = tf.transpose(X3,perm=[1,0])

X3  

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>